services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4y7sV96vA9wv46VR
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "/tmp:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
